pipeline {
    agent any
    
    tools {
	maven 'Maven3.9.11'
	}
    options {
        skipStagesAfterUnstable()
    }
    environment{
	JAVA_HOME = '/usr/lib/jvm/java-17-openjdk-amd64'
	PATH = "${JAVA_HOME}/bin:${env.PATH}"
	}
    stages {
	stage('Check Java'){
	    steps{
		sh'echo $JAVA_HOME'
		sh'java -version'
		sh'javac -version'
		}
	}
	stage('Checkout'){
	    steps{
		checkout scm
	    }
	}
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
	stage('Package'){
	    steps{
		archiveArtifacts artifacts: 'target/*.jar',fingerprint: true
		}
	}
        stage('Deliver') { 
            steps {
                echo 'Deploying build artifact... (placeholder)'
            }
        }
    }
}

