pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
	stage('Checkout'){
	    steps{
		checkout scm
	    }
	}
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
	stage('Package'){
	    steps{
		archiveArtifacts artifacts: 'target/*.jar',fingerprint: true
		}
	}
        stage('Deliver') { 
            steps {
                echo 'Deploying build artifact... (placeholder)'
            }
        }
    }
}

